### ISSUE TITLE
Materials added to Tinkers by Content Tweaker are not detected

### ISSUE THREAD

**Issue by Dragnier** [YaibaToKen/Armory-Expansion#10]
I've created a few materials (with traits) using Content Tweaker as stated in the title, but they do not get detected and converted to be usable in Construct's Armory by your mod.

**Comment by YaibaToKen** [comment]
I'm not entirely sure if I can get traits to be directly translated for armor, but I'll look into the materials part, hopefully it should be simple, though I take it you'd also like to be able to change the values?

**Comment by Dragnier** [comment]
Well, I have also asked on Constructs Armory github to have them add their own version of Content Tweaker support similar to Tinkers. If they do that, then anyone will be able to add their own materials and traits. Your mod is great for those who don't want to get that into coding though and just being able to get the armor values to generate would be awesome; whether the traits do or not.

**Comment by YaibaToKen** [comment]
As integration has been added by Construct's Armory, I will be closing this issue ;) feel free to reopen if anything else is needed.
