### ISSUE TITLE
[Enhancement] Redstone Arsenal and Simply Jetpacks integration

### ISSUE THREAD

**Issue by Trinsdar** [YaibaToKen/Armory-Expansion#12]
Could you add redstone arsenol, redstone repository, and simply jetpacks intergration?
I was thinking jetpacks/jetplates could be used as modifiers.

**Comment by Jackiecrazy** [comment]
Please also add Ice & Fire dragon/death worm scales, stymphalian feathers, troll leather etc!

**Comment by YaibaToKen** [comment]
As soon as the new material system is in the place, there are plans to add integration of this kind

**Comment by YaibaToKen** [comment]
@Trinsdar what sort of integration were you looking for in regards to Redstone Arsenal?

**Comment by Trinsdar** [comment]
I'll have to look back and see what I was thinking of back then. I'm guessing it was redstone arsenal would be a material that might have fe support or something like that.

**Comment by YaibaToKen** [comment]
@Trinsdar I would like to not step on the TiC development team's toes as it was their decision to remove the capacitor modifier. You can already make a tool unbreakable with the current modifiers and you can make it self repairing with mending moss.

**Comment by Trinsdar** [comment]
Well I have no idea what I even wanted then.

**Comment by YaibaToKen** [comment]
Feel free to open new issues with other suggestions but if possible, stick to one mod support request per issue

**Comment by YaibaToKen** [comment]
@Jackiecrazy check out version 1.1.3b as it has partial Ice and Fire support
