### ISSUE TITLE
Unable to repair.

### ISSUE THREAD

**Issue by Mrbysco** [YaibaToKen/Armory-Expansion#14]
I originally made some full steel armor and then changed some parts out for Demon Ingot(extrautils2).
The issue is. My armor broke and I'm now unable to repair it with either of the two.

Some images:
![armor parts](https://i.imgur.com/ZJS5QmD.png)

![repair with steel](https://i.imgur.com/GSaCcQP.png)

![repair with demon](https://i.imgur.com/3QOxXY5.png)

**Comment by YaibaToKen** [comment]
I'll be updating the mod to the latest versions of TiC and Construct's Armory later today, hopefully that'll solve it, but otherwise, there's nothing in my code that could bork that part of the mod :/ if the update doesn't fix it, an issue will have to be opened with the Construct's Armory Dev

**Comment by Mrbysco** [comment]
This issue seems to be on Extra Utilities side as I just found out I'm even unable to repair normal demonic tools. https://github.com/rwtema/Extra-Utilities-2-Source/issues/189

**Comment by YaibaToKen** [comment]
I shall close this issue then
