### ISSUE TITLE
[1.12.2] Many Materials Have 0/-0,42 Defense and 0/-0,25 Durability

### ISSUE THREAD

**Issue by Draskh** [YaibaToKen/Armory-Expansion#15]
As the title says. I do not think, that this is intended.

![2018-10-10_02 20 03](https://user-images.githubusercontent.com/26455012/46706137-494d4800-cc33-11e8-9cb9-1bded1461e63.png)
![2018-10-10_02 20 05](https://user-images.githubusercontent.com/26455012/46706138-49e5de80-cc33-11e8-8e8f-aa549a915138.png)
![2018-10-10_02 20 07](https://user-images.githubusercontent.com/26455012/46706139-49e5de80-cc33-11e8-832e-0bd378ba77c4.png)
![2018-10-10_02 20 13](https://user-images.githubusercontent.com/26455012/46706140-49e5de80-cc33-11e8-8a0c-3544fd2ac731.png)
![2018-10-10_02 20 17](https://user-images.githubusercontent.com/26455012/46706141-49e5de80-cc33-11e8-937f-47a2d8a6c662.png)
![2018-10-10_02 20 22](https://user-images.githubusercontent.com/26455012/46706142-49e5de80-cc33-11e8-8a23-0c6515a2a23f.png)
![2018-10-10_02 20 28](https://user-images.githubusercontent.com/26455012/46706143-4a7e7500-cc33-11e8-9a5d-1eb490ec1c0a.png)
![2018-10-10_02 20 34](https://user-images.githubusercontent.com/26455012/46706144-4a7e7500-cc33-11e8-85d3-05d1a064f352.png)
![2018-10-10_02 20 42](https://user-images.githubusercontent.com/26455012/46706145-4a7e7500-cc33-11e8-92de-21a4ed95ddf6.png)
![2018-10-10_02 20 44](https://user-images.githubusercontent.com/26455012/46706147-4a7e7500-cc33-11e8-9c85-9de59a73faf8.png)
![2018-10-10_02 19 13](https://user-images.githubusercontent.com/26455012/46706148-4a7e7500-cc33-11e8-8ecf-c961b8a5ade6.png)
![2018-10-10_02 19 42](https://user-images.githubusercontent.com/26455012/46706149-4a7e7500-cc33-11e8-859a-2a20c8831a55.png)
![2018-10-10_02 19 45](https://user-images.githubusercontent.com/26455012/46706150-4b170b80-cc33-11e8-97f4-87f386508f7d.png)
![2018-10-10_02 19 47](https://user-images.githubusercontent.com/26455012/46706151-4b170b80-cc33-11e8-96a3-eaadeb5601ae.png)
![2018-10-10_02 19 50](https://user-images.githubusercontent.com/26455012/46706152-4b170b80-cc33-11e8-81ff-82827c45f60f.png)
![2018-10-10_02 19 55](https://user-images.githubusercontent.com/26455012/46706153-4b170b80-cc33-11e8-9b18-1724798f64d8.png)
![2018-10-10_02 19 58](https://user-images.githubusercontent.com/26455012/46706154-4b170b80-cc33-11e8-8782-a75ed6c604f4.png)

**Comment by YaibaToKen** [comment]
It is indeed not intended and a rework of the stat calculation is in order to solve this and (hopefully) other similar issues :) thanks for the heads-up nonetheless

**Comment by YaibaToKen** [comment]
Should be fixed since version 1.1.3c
