### ISSUE TITLE
Avaritia 1.1x Support

### ISSUE THREAD

**Issue by RoyalReject** [YaibaToKen/Armory-Expansion#19]
Kinda think it would be cool to be able to fight chaos dragon and stuff without needing to make the Draconian Armour

**Comment by YaibaToKen** [comment]
At this point in time, all the mod does is convert TiC support added by mods into CA support by applying some calculations to the materials stats and generating the corresponding armor stats. If Avaritia has native TiC support or if you're using a mod that adds TiC support for Avaritia, my mod should pick that up and add CA support.
