### ISSUE TITLE
Crash when used with flans mod.

### ISSUE THREAD

**Issue by malice936** [YaibaToKen/Armory-Expansion#2]
[Crash Report](https://pastebin.com/NDpeFm0s)
Crashes on startup, not sure if it's flans or your mod causing it, will report to the flans dev as well.

**Comment by YaibaToKen** [comment]
Seems to be a problem with Flans Mod Apocalypse, not really sure what is causing it. Does it happen without Armory Expansion?

**Comment by malice936** [comment]
Unfortunately no it doesn't occur when I remove your mod, and it also doesn't occur when I remove flans, but the 2 together in my private pack seem to have some sort of incompatibility. I would also like to note that I'm fairly sure there's a 3rd culprit at this point because I made a new instance with just your mod and flans and there wasn't a crash, so I've been going through and gradually adding mods a few at a time to figure out what the 3rd culprit is, I will keep you updated if I figure it out. Thanks for the time though.

**Comment by YaibaToKen** [comment]
Lemme know if you figure out the conflicting mod so I can try to figure out a fix

**Comment by YaibaToKen** [comment]
Closed due to lack of response
