### ISSUE TITLE
[Enhancement] Integration for Mekanism Materials?

### ISSUE THREAD

**Issue by FriendlyGamer** [YaibaToKen/Armory-Expansion#23]
Hi I am currently using PlusTiC but it's limited to tools and alternative smeltry recipes for the most part, would it possible for this mod to integrate with the Mekanism mod materials like the Refined Obsidian and other materials for BOTH tools and armory if that add on is installed? Or if it already included as of now?  

Thanks in advance!

**Comment by YaibaToKen** [comment]
Currently, the mod only adds ConArm support to mods with TiC support in place, be it through themselves or add-ons. The exception being Ice and Fire as of the latest release which has part of the materials integrated with the rest coming soon.

**Comment by FriendlyGamer** [comment]
> Currently, the mod only adds ConArm support to mods with TiC support in place, be it through themselves or add-ons. The exception being Ice and Fire as of the latest release which has part of the materials integrated with the rest coming soon.

Does that means if an add on already add TiC support for a material this would extend that to armor as well if they don't provide that support themselves?  Thanks in advance.

**Comment by YaibaToKen** [comment]
> > Currently, the mod only adds ConArm support to mods with TiC support in place, be it through themselves or add-ons. The exception being Ice and Fire as of the latest release which has part of the materials integrated with the rest coming soon.
> 
> Does that means if an add on already add TiC support for a material this would extend that to armor as well if they don't provide that support themselves? Thanks in advance.

That's right

**Comment by YaibaToKen** [comment]
What materials still lack support?

**Comment by YaibaToKen** [comment]
Closed due to lack of response and info.
