### ISSUE TITLE
1.1.3c crashes dedicated server Forge 1.12.2 build 2824 class not found

### ISSUE THREAD

**Issue by kreezxil** [YaibaToKen/Armory-Expansion#24]
First I do indeed have 1.1.3c installed

![Screenshot_1](https://user-images.githubusercontent.com/3880072/55346477-35fb9680-5478-11e9-828b-aa23926eaf79.png)

however in the crash report it shows as 1.1.3b. This tells me your filename is 1.1.3b but your mod.info isn't.

That's minor compared to what appears to be the mod looking for client side classes on a server.

crash report:
http://paste.ubuntu.com/p/Bv26c72k8t/

fml server latest:
http://paste.ubuntu.com/p/RVtwP953Dt/

**Comment by YaibaToKen** [comment]
@kreezxil I forgot to remove a dependency on the integration plugin so I did that and a quick rebuild without changing the version number in the code. As for the crash, I'm aware of it but didn't know exactly what was causing that so thanks. Guess I'll be working on fixing that this week.
