### ISSUE TITLE
[Enhancement] Custom modifier/trait support in AbstractIntegration

### ISSUE THREAD

**Issue by SokyranTheDragon** [YaibaToKen/Armory-Expansion#28]
I've wanted to contribute a little bit and add some new modifiers/traits (I've made them some time ago as I started working on Tinker's Support for Ice & Fire some time ago). It seems like there's no designed place for them in AbstractIntegration.

I don't really want to mess around with your design of the project, so I'll let you decide on how you want to handle it. I'll take care of implementing modifiers/traits.

If you'd like to discuss this outside of github then I'm willing to provide some contact info.

I could implement this myself if you'd like me to do so.

**Comment by SokyranTheDragon** [comment]
Now that I'm looking at it, adding custom fluids (without a material with them) would also be nice (for molten sapphire).

**Comment by YaibaToKen** [comment]
@exploder1531 the API in place does need some rework as it does not support custom traits or fluid registration atm.
While not entirely an oversight, it is a necessity for further expansion of the mod's content and as such, will be looked at. Fluids however are something I've never handled so it might be better to wait till mmdlib goes stable and the mod can be migrated to rely on it instead.
On that note, feel free to ping me in MMD's discord for further discussion :) username is the same as GitHub

**Comment by YaibaToKen** [comment]
@exploder1531 several big changes have been made to the system so you might want to check it out again. On another note, how can I easily contact you? Discord would be welcome.

**Comment by YaibaToKen** [comment]
Closed due to lack of response
