### ISSUE TITLE
[Enhancement][Feedback] New config options.

### ISSUE THREAD

**Issue by SirAron111** [YaibaToKen/Armory-Expansion#31]
Configuration or Armor and tool parts are a nice thing especially for a modpack maker like me who needs to adjust all the values to make them fit the rising difficulty and the higher dmg in my modpack but there are some things I think could be made better in your config files. For example here is how the ConstructsArmory.zs handles it.

val manyullyn = <conmat:manyullyn>;
manyullyn.durabilityCore=80;
manyullyn.durabilityPlates=40;
manyullyn.durabilityTrim=1;
manyullyn.modifier=5;
manyullyn.defense=60;
manyullyn.toughness=4;

 This in turn would set all the armors values to exactly the values specified above (just not the toughness that one doesn’t change for some reason never figured out why)

In your config on the other hand I can’t specifically set how much durability plates/trims/core parts have. This means I can’t apply my changes of having plates have half of core durability and the trim having just 1 to make it be only the optional part for the effect of choice.

Also its hard to know what which value does for example I set the dragons scales to have 50 durability and 8 dmg but for some reason in game it set them to ridiculous amounts of dmg and durability etc. like 0 durability instead of the 50 I set

AS for bows and stuff it’s hard to know to what I should set stats like range and accuracy? For example if I want to get 100 accuracy from myrmex fletch lings do I set accuracy to 100.0 or 1.0 also what is hardness… I think you should implement in the config option right at the top of it an explanation on how to set values and how they affect what stat. And also make it so that the stats set here are the ones you actually get so if I set values like 45 for defense I would like to get 45 and not 90 and if the values set are just modifying the stats by multiplication instead of overwriting them you should give an example for the calculation and maybe add the default values of the materials for each stat next to the materials so you don’t have to go in game to edit it all the time since it’s hard to do with big packs that need more than 5 mins to load up

BTW. Is there no way to edit the bonus dmg for the bow material or the bow individually as well as the draw speed? For some reason I have +20 bonus dmg on dragon bone bows and a draw speed of 10 meaning ye I have dmg but flip am I slow XD or is that also a problem of one value change affecting multiple stats differently in game.

Also a list with all the modifiers that I could add to the different parts of armor would be nice before going through the config I never even know that the effects for armor need a _armor after it.

You should also consider splitting the config up a bit nicer. So instead of putting all in one put the config for armor parts in one .json and the config for tool parts in another one. That way you can easier apply the different values like durability without affecting the values of the other stat materials stats. And then handle the disable enable in the main config.csg instead of the. Json

Also is it not possible to have the ice and fire config merged with the standard materials config? Having them both is kind of strange thought I like the layout of the new armoryexpansion-iceandfire.csg

Also you should make it so that if there are multiple materials of the same type like emeralds and plustic_emeralds that only one gets added and used at all so people don’t have to set 2 different ones to false/true or find 2 different ones in the jei even thought the game itself prioresses one over the other and only casts that one anyway.

Ok that’s it for now this is btw not a complain even if it sounds like it Xd I simply wanted to give a detailed feedback.

GZ
SirAron

**Comment by SirAron111** [comment]
I also found a few things that didn’t make sense for example disabling or enabling bonedragon in the stats json or the armory ice and fire .csg  didn’t change anything as it was still (for some reason the only ice and fire material) that was enabled in the normal .csg of armory expansion or even in there at all

**Comment by YaibaToKen** [comment]
> Configuration or Armor and tool parts are a nice thing especially for a modpack maker like me who needs to adjust all the values to make them fit the rising difficulty and the higher dmg in my modpack but there are some things I think could be made better in your config files. For example here is how the ConstructsArmory.zs handles it.
> 
> val manyullyn = conmat:manyullyn;
> manyullyn.durabilityCore=80;
> manyullyn.durabilityPlates=40;
> manyullyn.durabilityTrim=1;
> manyullyn.modifier=5;
> manyullyn.defense=60;
> manyullyn.toughness=4;
> 
> This in turn would set all the armors values to exactly the values specified above (just not the toughness that one doesn’t change for some reason never figured out why)

Do keep in mind that you should be able to change the stats for my materials using ZS the same way you can do it for ConArm. If that isn't happening, please do open an issue for it.

> Also its hard to know what which value does for example I set the dragons scales to have 50 durability and 8 dmg but for some reason in game it set them to ridiculous amounts of dmg and durability etc. like 0 durability instead of the 50 I set

That's a problem with the formulas I use to set the stats. Still not sure on how I want to handle that, whether I'll simply place the formulas in a comment at the top of the JSON files or I'll switch to straight up using the values in the files.

> AS for bows and stuff it’s hard to know to what I should set stats like range and accuracy? For example if I want to get 100 accuracy from myrmex fletch lings do I set accuracy to 100.0 or 1.0 also what is hardness… I think you should implement in the config option right at the top of it an explanation on how to set values and how they affect what stat. And also make it so that the stats set here are the ones you actually get so if I set values like 45 for defense I would like to get 45 and not 90 and if the values set are just modifying the stats by multiplication instead of overwriting them you should give an example for the calculation and maybe add the default values of the materials for each stat next to the materials so you don’t have to go in game to edit it all the time since it’s hard to do with big packs that need more than 5 mins to load up

Accuracy is set as a decimal, which means that `1.0` represents `100%`.
Explaining what each field does sounds like a must at this time.

> In your config on the other hand I can’t specifically set how much durability plates/trims/core parts have. This means I can’t apply my changes of having plates have half of core durability and the trim having just 1 to make it be only the optional part for the effect of choice.

> BTW. Is there no way to edit the bonus dmg for the bow material or the bow individually as well as the draw speed? For some reason I have +20 bonus dmg on dragon bone bows and a draw speed of 10 meaning ye I have dmg but flip am I slow XD or is that also a problem of one value change affecting multiple stats differently in game.

While it would definitely be a huge quality of life improvement, separating the values used so much would bloat the JSON objects to unwieldy sizes.

> Also a list with all the modifiers that I could add to the different parts of armor would be nice before going through the config I never even know that the effects for armor need a _armor after it.

All traits registered with TiC before the mod is loaded should be valid. I'll look into setting the mod to export a file with all the existing traits on load. The field names in the JSON are very much work in progress but as it was a long awaited feature by the community, I went ahead and made a release.
Do note that I'm planning to push a new release that makes it so all materials use the system in place for Ice and Fire.

> You should also consider splitting the config up a bit nicer. So instead of putting all in one put the config for armor parts in one .json and the config for tool parts in another one. That way you can easier apply the different values like durability without affecting the values of the other stat materials stats. And then handle the disable enable in the main config.csg instead of the. Json

Unfortunately, splitting the JSON files into Tools and Armor isn't feasible at the moment.

> Also is it not possible to have the ice and fire config merged with the standard materials config? Having them both is kind of strange thought I like the layout of the new armoryexpansion-iceandfire.csg

Each integration currently gets it's own `#.cfg` and `#.json` file, this so users know which integration adds each material.

> Also you should make it so that if there are multiple materials of the same type like emeralds and plustic_emeralds that only one gets added and used at all so people don’t have to set 2 different ones to false/true or find 2 different ones in the jei even thought the game itself prioresses one over the other and only casts that one anyway.

TiC handles the materials based on the identifier used when registering the material, that identifier represents the ore dictionary entry for valid items. Currently, I name the materials based on Forge's OreDict Entry naming conventions.

Thanks for the feedback, it's much appreciated.

**Comment by SirAron111** [comment]
Thx for the fast answers and explanations. I will mess around a bit more with the files especially the armor durability values and a way t get the stats t be roughly to be balanced with my pack if I have the time. Until then I will just disable all materials that I can’t set properly like I did before.
Well than until the next update. And good luck.

**Comment by YaibaToKen** [comment]
Hoping I can bother you to test the 1.1.8 beta file. It should also allow users to add new materials though it still lacks localization support.

**Comment by SirAron111** [comment]
If it’s on curse in the recently updated ones I will probably test it anyway, as I always update my modpacks test environment to make sure the next update has all the fixes for bugs and stuff as well as the updated versions of mods so I will np I will also try to give a feedback again after testing it.

**Comment by YaibaToKen** [comment]
I had to retract the release due to a crash that didn't show in dev. Will release an update as soon as that's fixed. Thanks

**Comment by YaibaToKen** [comment]
@SirAron111 any way I can contact you outside of GitHub? Discord would be a good way.

**Comment by SirAron111** [comment]
Feel free to join my discord server for my Modpack I am mostly reachable there. Simply PM me there!

https://minecraft.curseforge.com/projects/dimension-zero the discord link is on this page.
