### ISSUE TITLE
Integration Suggestions

### ISSUE THREAD

**Issue by TheLimePixel** [YaibaToKen/Armory-Expansion#4]
As Modern Skyblock 3 probably has the most Tinker's Construct materials, here are all the mods that have TiC support that aren't supported by Armory Expansion:
- Mystical Agradditions
- Silent's Gems
- Extra Utilities
- Ender IO

**Comment by YaibaToKen** [comment]
The latest version of Ender IO should have construct's armory support. I'll look into adding the other though ;) thanks for telling me

**Comment by TheLimePixel** [comment]
Hmm... under further examination, it seems that Extra Utilities, EnderIO and Mystical Agradditions' materials are in the Armory manual. Does that mean they would work?

**Comment by YaibaToKen** [comment]
If they show up in the manual then they are available. Traits however might not be fully working ;)

**Comment by YaibaToKen** [comment]
Ender IO and Extra Utilities support has been added, Mystical Agradditions will soon follow
