### ISSUE TITLE
Double registration of stats with PlusTiC

### ISSUE THREAD

**Issue by OneEyeMaker** [YaibaToKen/Armory-Expansion#42]
PlusTiC in recent version (7.0.7.0) added registration of stats for peridot armor:
https://github.com/Landmaster/PlusTiC/commit/96f5b74c5c4656575aee14d81406275cfad74e80#diff-6679557ce3e932aa726879c2ca21e737

With ArmoryExpansion (1.2.4) this causes crash:
https://pastebin.com/AqZ6Dbmh

**Comment by YaibaToKen** [comment]
That's quite the oversight on my end...
Meanwhile, did you try to delete config/armory-expansion/conarm-materials.json?

**Comment by OneEyeMaker** [comment]
Removing config file resolves issue.
After loading game there's no entry for peridot in config.

**Comment by YaibaToKen** [comment]
Thanks, I know what's causing it then

**Comment by YaibaToKen** [comment]
Ok, so I checked and the code already tests if the material exists before registering it :/ I'll close it as I can't seem to reproduce.
