### ISSUE TITLE
Armor is not colored

### ISSUE THREAD

**Issue by pupnewfster** [YaibaToKen/Armory-Expansion#44]
Using armory expansion version 1.2.5, I can confirm that #36 is now fixed, HOWEVER, now all types that are registered by armory expansion are not colored. (might just be only PlusTiC ones that are not colored, not fully sure). https://gyazo.com/9ce7191fc6540b3acf22b7a12cf14919

**Comment by YaibaToKen** [comment]
It was a registration timing issue in the ConArm Integration module. Fixed in dev and will be in the next update as it's not game breaking.
