### ISSUE TITLE
Extra Utilities 2 Support Bug

### ISSUE THREAD

**Issue by ToMe25** [YaibaToKen/Armory-Expansion#5]
Extra Utilities Tool Materials will not be added as Armor Material if Moar Tinkers isnt loaded.

I am using:
Forge 14.23.4.2703,
Mantle 1.3.2.24,
TInkers Construct 2.10.1.84,
conarm 0.0.20-b,
Extra Utilities 2 1.7.6
And some times: Moar Tinkers 0.5.4

Without Moar Tinkers:
![2018-06-05_17 20 10](https://user-images.githubusercontent.com/38815969/40986015-85b628d6-68e5-11e8-8eb6-ba34639f3f78.png)

And with Moar Tinkers: 
![2018-06-05_17 23 47](https://user-images.githubusercontent.com/38815969/40986061-9c3f4ff6-68e5-11e8-93fb-c0171da57df4.png)

**Comment by YaibaToKen** [comment]
The current system simply looks for materials with tool parts and generates the corresponding armor parts. Moar Tinkers is the one with Extra Utilities support, I just add armor support for existing materials ;)

**Comment by ToMe25** [comment]
Extra Utilities 2 has TC support by it self.
It adds all Tool Materials.
Without MoarTinkers:
![2018-06-05_19 41 45](https://user-images.githubusercontent.com/38815969/40992960-84a1f4a8-68f8-11e8-935c-ea7705d2cf29.png)

**Comment by YaibaToKen** [comment]
Oh, apologies, didn't know that. Should be an easy fix then, lemme get a new build ready

**Comment by ToMe25** [comment]
Thanks for Reply :) and Thaks for Fixing it!

**Comment by YaibaToKen** [comment]
Build awaiting curse approval ;)
