### ISSUE TITLE
crash with latest update

### ISSUE THREAD

**Issue by border999** [YaibaToKen/Armory-Expansion#52]
https://paste.dimdev.org/vikagedoci.mccrash

**Comment by jusitnboggs** [comment]
Same here
https://pastebin.com/nsVfxVhS

**Comment by katubug** [comment]
And here! https://paste.dimdev.org/equtasovez.mccrash

**Comment by katubug** [comment]
Deleting the config folder and the armoryexpansion.cfg in /config/ allows the game to start.

**Comment by border999** [comment]
good to know, that should be a disclaimer on the curseforge page

**Comment by YaibaToKen** [comment]
I'll add the disclaimer today. Meanwhile, I'll consider this as solved
