### ISSUE TITLE
Crash on loadup of Armory Expansion 1.3.1

### ISSUE THREAD

**Issue by SirAron111** [YaibaToKen/Armory-Expansion#54]
Crash on loadup of Armory Expansion 1.3.1 here is the report https://pastebin.com/pBnfFttk 
Minecraft Version 1.12.2
Forge Version 14.23.5.2838

(Note I have configs from the previous version already created with altered contents (added effects etc to cores plates of dragon serpent mermyx parts etc not changed anything in the normal materials or custom materials stuff thought))

Modpack used Dimension Zero (8.0)

**Comment by YaibaToKen** [comment]
Delete all the files ending in `-config.json` in the `armory-expansion` folder, inside your config folder. Afaik those are the only files you need to delete.

**Comment by SirAron111** [comment]
custommaterials-config and conarm-config and iceandfire-config will try that later
----Worked some new armor mats popped up i need to adjust now like (Natura/Draconic/Botania stuff and 2 strange materials from matter overdrive (mod that’s not in the pack thought) dilithium and tritanium)
-----------After adding changing the stats with the craft weaker script how I did it with all other materials to the material effects such as Mana on botania stuff vanished. But only from the new ones all other materials are fine. Here a few pictures to show you what i mean (and some of the normal materials that still have the stats)
![2019-06-03_19 40 05](https://user-images.githubusercontent.com/39855956/58822293-796caf80-8637-11e9-84a8-af2deed8ec2d.png)
![2019-06-03_19 40 12](https://user-images.githubusercontent.com/39855956/58822294-7a054600-8637-11e9-978f-de0829233b12.png)
![2019-06-03_19 39 22](https://user-images.githubusercontent.com/39855956/58822295-7a054600-8637-11e9-9841-804c7bb7b594.png)
![2019-06-03_19 39 25](https://user-images.githubusercontent.com/39855956/58822296-7a054600-8637-11e9-92b4-92e25121cba6.png)
![2019-06-03_19 39 29](https://user-images.githubusercontent.com/39855956/58822297-7a054600-8637-11e9-818b-2bb7d03833a1.png)
![2019-06-03_19 39 31](https://user-images.githubusercontent.com/39855956/58822299-7a054600-8637-11e9-831c-70c5206a307f.png)
![2019-06-03_19 39 51](https://user-images.githubusercontent.com/39855956/58822302-7a9ddc80-8637-11e9-949a-f580b9992f16.png)
![2019-06-03_19 40 02](https://user-images.githubusercontent.com/39855956/58822303-7a9ddc80-8637-11e9-9fcd-c9a066a5de41.png)

Here is a copy of my ConstructsArmory.zs script in pastbin
https://pastebin.com/jH4fu5rp

**Comment by YaibaToKen** [comment]
Yeah, currently the materials still get registered even if the required mod isn't loaded. Ore dictionary entries simply won't be generated for those materials. Next version will include a way to customize the ore dictionary entries for each material. Meanwhile you can disable the materials you don't want in the new `-config.json` files.
