### ISSUE TITLE
added materials are incompatible with mending moss

### ISSUE THREAD

**Issue by ryan-rmlabs** [YaibaToKen/Armory-Expansion#59]
it seems that armor created with added materials are interacting wrongly with mending moss and can only gain XP through damage done by jagged/spiny modifiers

**Comment by YaibaToKen** [comment]
That seems extremely weird, as there isn't any special handling needed for adding new materials, only a matter of registering the stats.

**Comment by ryan-rmlabs** [comment]
but that is what I am experiencing, I can show proof, but I think there may have been some unintentional error in the code, or some other strange kink that may result in this bug

**Comment by ryan-rmlabs** [comment]
never mind, It seems that the conflict seems to be between the rough/jagged/spiny modifiers and the mending moss, it seems that they modifiy traditional XP collection, thus my results

**Comment by YaibaToKen** [comment]
As it seems this is not a problem with Armory Expansion but with TiC and ConArm, I'll be closing this
