### ISSUE TITLE
Crash on Forge server with AE 0.1.1

### ISSUE THREAD

**Issue by Bulldog83** [YaibaToKen/Armory-Expansion#6]
Minecraft 1.12.2
Forge 14.23.4.2705
AE 0.1.1

https://gist.github.com/Bulldog83/55207c3696fe624b8753990426e1fede
Also look at server-log file.

**Comment by border999** [comment]
I recommend someone get this issue dealt with quickly

**Comment by YaibaToKen** [comment]
I missed two ; in the dependencies list, really sorry, will be dealt with today, as soon as I get off from work :(

**Comment by YaibaToKen** [comment]
fixed in version 0.1.1a
