### ISSUE TITLE
Plate Modifier stat balance

### ISSUE THREAD

**Issue by lamoyrl90** [YaibaToKen/Armory-Expansion#70]
The plates' modifiers are currently calculated the same as the core defense stat, but according to other mods' ConArm support a better representation would be through the handle's modifier stat in TiCon. Should be a simple enough fix, and it would represent a huge balance fix. As it stands, materials from your mod are roughly 30x more durable as plates than any other material.

**Comment by YaibaToKen** [comment]
Thanks for the heads up, I'll be sure to upload a version with this change asap. :)

**Comment by lamoyrl90** [comment]
Cool! Love the mod, by the way. It's nice having more choices to play around with as far as armor goes.

**Comment by YaibaToKen** [comment]
That's precisely what led me to create it :) Back when ConArm was released, you only had the default TiC materials and some common metals available. For someone that used and abused TiC add-ons, not having them for armour parts was a nightmare.
