### ISSUE TITLE
Simple TCon/SimpleOres incompatibility, Wearing any Simpleores armor uses Iron/white 3D model

### ISSUE THREAD

**Issue by E4XeniTh** [YaibaToKen/Armory-Expansion#73]
Simple TCon/SimpleOres incompatibility:
Wearing any armor from SimpleTcon uses Iron/white armor 3D model on the player

Mods used while debugging (1.12.2):
Mantle
Tinkers Construct
Construct's Armory
[SimpleCore API](https://www.curseforge.com/minecraft/mc-mods/simplecore-api)
[SimpleOres](https://www.curseforge.com/minecraft/mc-mods/simpleores)
[Simple Tcon](https://www.curseforge.com/minecraft/mc-mods/simple-tcon)
This mod

The color code in conarm-materials.json seems to be completely ignored aswell.

![image](https://user-images.githubusercontent.com/64338026/80294353-d2ba6180-8768-11ea-89d2-725805685af9.png)

![image](https://user-images.githubusercontent.com/64338026/80294591-cafbbc80-876a-11ea-8308-5bd170e286bd.png)

**Comment by YaibaToKen** [comment]
Does this not happen for the tool parts?

**Comment by E4XeniTh** [comment]
No,
The tool parts are registered by Simple TCon, which adds nothing else.
Apologies for not noting that in the first place.

**Comment by YaibaToKen** [comment]
Thanks, I'll take a look at it

**Comment by YaibaToKen** [comment]
Afraid I don't know why this happens and am not entirely sure if this is an issue on my mod  or on Construct's Armory side :/

**Comment by TheOldOne822** [comment]
I've found the issue on my end. Will be updating Simple TCon soon.
Had some code leftover from 1.10 that was no longer needed in 1.12, removing it fixed armor render.
