### ISSUE TITLE
Crashed my Game

### ISSUE THREAD

**Issue by jec0218** [YaibaToKen/Armory-Expansion#75]
Here is the crash log
https://www.dropbox.com/s/027e91p5g5ywil4/crash-2020-05-26_10.00.45-client.txt?dl=0

**Comment by YaibaToKen** [comment]
I'll start by asking you to make a list of the strictly necessary mods needed to reproduce this crash.

**Comment by YaibaToKen** [comment]
Closing due to lack of info and response in nearly 3 months.
