### ISSUE TITLE
Constant Crashing After Bluescreen

### ISSUE THREAD

**Issue by ZeroHearts** [YaibaToKen/Armory-Expansion#77]
So I was launching the Dimension Zero modpack today, and my PC bluescreened for the first time in over a year. I thought nothing of it and just restarted it and went back to trying to play. However ever since the bluescreen, I get an error message saying that every Armory Expansion 'mod' is corrupted and I'm not able to even launch the game. I talked with the pack author and they suggested I come this way. I hope my changelog helps but if I can provide any extra info please do let me know!
[crash-2020-07-01_15.55.06-client.txt](https://github.com/MinecraftModDevelopmentMods/Armory-Expansion/files/4860336/crash-2020-07-01_15.55.06-client.txt)

**Comment by YaibaToKen** [comment]
Please post the crash log using a service such as hastebin or gist. Thank you.

**Comment by ZeroHearts** [comment]
> Please post the crash log using a service such as hastebin or gist. Thank you.

I believe this should work then? https://hastebin.com/ocinehaviz.rb

**Comment by YaibaToKen** [comment]
Are you using the latest mod version available on CurseForge? Have you made any changes to the mod's config files? Have you tried doing a fresh install of the modpack?

**Comment by ZeroHearts** [comment]
I did a fresh install of the pack and it works now. I was using the latest version, I even downloaded a new mod file and replaced the old one in the old pack and it still wouldn't work. So I have a workaround but its still something I'm concerned about for the future/for others. 

I assume it has something to do with getting a bluescreen while it launched as it gave me a .error file for the Ice and Fire compatibility config, but even deleting that didn't fix it.

**Comment by YaibaToKen** [comment]
Each Armory Expansion plugin has 4 json files.
Example: 
![image](https://user-images.githubusercontent.com/9133736/86392748-df40c600-bc93-11ea-895c-414d50fed955.png)

Did you try deleting all 4 of them when you deleted the error file?

**Comment by ZeroHearts** [comment]
> Each Armory Expansion plugin has 4 json files.
> Example:
> ![image](https://user-images.githubusercontent.com/9133736/86392748-df40c600-bc93-11ea-895c-414d50fed955.png)
> 
> Did you try deleting all 4 of them when you deleted the error file?

Where would I find those? When I deleted the Error file it was just a single file in the config folder, it wasn't inside another folder. I can try and retrieve it and send it your way if that might help?

**Comment by YaibaToKen** [comment]
No need, but I suspect something else went wrong with the JSON files. Either way, this seems to be solved for now.
