### ISSUE TITLE
help me please, as soon as possible, create materials.

### ISSUE THREAD

**Issue by DarkerFALLEN** [YaibaToKen/Armory-Expansion#79]
So, I've been learning to work on this mod lately and I have a very big doubt, how do you create new materials? I only know how to add armor until now, can someone help me by giving me an example of how I create the bow items and tools? and how is an alloy made of materials that I am creating?

**Comment by YaibaToKen** [comment]
Bowstring example:
https://github.com/MinecraftModDevelopmentMods/Armory-Expansion-Bits-And-Pieces/blob/5ea183c0747529981d498fc4ea3855ad2ab12bdf/src/main/resources/assets/armoryexpansion/data/bitsandpieces/bitsandpieces-materials.json#L2-L6

Bow example: 
https://github.com/MinecraftModDevelopmentMods/Armory-Expansion/blob/3296dd01994df85af142081c8b599b3e5721a5c1/src/main/resources/assets/armoryexpansion/data/matteroverdrive/matteroverdrive-materials.json#L34-L39

Arrowshaft example: 
https://github.com/MinecraftModDevelopmentMods/Armory-Expansion/blob/3296dd01994df85af142081c8b599b3e5721a5c1/src/main/resources/assets/armoryexpansion/data/matteroverdrive/matteroverdrive-materials.json#L40-L44

You can see an example of nearly all tool parts here:
https://github.com/MinecraftModDevelopmentMods/Armory-Expansion/blob/3296dd01994df85af142081c8b599b3e5721a5c1/src/main/resources/assets/armoryexpansion/data/matteroverdrive/matteroverdrive-materials.json#L3-L9

Alloy example:
```java
  {
    "inputs": {
      {
        "fluid": "copper",
        "amount": 1
      },
      {
        "fluid": "tin",
        "amount": 1
      },
    }
    "output": {
      "fluid": "bronze",
      "amount": 2
    }
  }
```
The amounts are in MB, the output amount doesn't have to be correspond to the sum of all input amounts. Take the example of Manyullyn, 1MB of Ardite with 1MB of Cobalt equals 1MB of Manyullyn.
