### ISSUE TITLE
Missing PlusTic draconic evolution and botania materials

### ISSUE THREAD

**Issue by spyguy26** [YaibaToKen/Armory-Expansion#8]
Armory expansion is not adding armor parts for the plustic materials, livingwood, terrasteel, mirion, manasteel, elementium, or any of the draconic evolution cores

I am using the latest version of armory expansion 0.1.1a

the materials in the standard materials and you
![2018-06-09_19 07 22](https://user-images.githubusercontent.com/39753561/41196867-2e9af504-6c19-11e8-8995-6b2e5fad606f.png)

the materials not in the armory addendum
![2018-06-09_19 07 00](https://user-images.githubusercontent.com/39753561/41196873-3e242b12-6c19-11e8-8a4f-4034a1177b3f.png)
![2018-06-09_19 07 02](https://user-images.githubusercontent.com/39753561/41196875-429113cc-6c19-11e8-9c3a-e20b146df0ca.png)

**Comment by YaibaToKen** [comment]
Could you please tell me what versions of plustic, botania, draconic evolution and the dependencies you are using? same for the forge version? I'll try to reproduce it and see what's going wrong in my code.

**Comment by spyguy26** [comment]
Sure!
I'm using
Botania+r1.10-354
Baubles-1.12-1.5.2 
Draconic-Evolution-1.12-2.3.11.290-universal
BrandonsCore-1.12-2.4.2.157-universal
CodeChickenLib-1.12.2-3.1.8.341-universal
TConstruct-1.12.2-2.10.1.84
Mantle-1.12-1.3.1.21
plustic-6.5.2.0
conarm-1.12.2-0.0.20-b

and my forge is
forge-1.12.2-14.23.4.2703-universal

**Comment by YaibaToKen** [comment]
Thanks, will take a look. Though, just one question, have you tried resetting the config file?

**Comment by spyguy26** [comment]
Yes I have reset the config twice and no luck

**Comment by spyguy26** [comment]
Update this issue is still present in the latest version 0.1.2

**Comment by YaibaToKen** [comment]
Sorry, the latest update was simply adding support for another mod, unfortunately I wasn't home yesterday and the day before I couldn't download the mods from curseforge to test for some reason, will be taking a look at it this weekend though

**Comment by ToMe25** [comment]
I have made a list of all Missing PlusTiC Materials:
ToolMaterial(mod that adding the used Item)
Livingwood(Botania)
Manasteel(Botania)
Elementium(Botania)
Terrasteel(Botania)
Mirion(PlusTiC)
Wyvern(Draconic Evolution)
Awakened(Draconic Evolution)
Chaotic(Draconic Evolution)
Pink Slime(Industrial Foregoing)
Red Matter(ProjectE)
Dark Matter(ProjectE)
Bloodwood(Natura)
Fusewood(Natura)
Ghostwood(Natura)
Darkwood(Natura)
Emerald(Minecraft)


Using:
the same things like @spyguy26 except of Mantle,
Industrial Foregoing 1.12.2-1.10.1-176,
Mantle 1.12-1.3.2.24,
Natura 1.12.2-4.3.2.49,
Jei 1.12.2-4.9.1.188,
CCL 1.12.2-3.1.9.344,
ProjectE 1.12-1.3.0

**Comment by YaibaToKen** [comment]
I'll be taking a look this weekend, I have an idea on what might be causing this and the planned rewrite to how I filter materials should hopefully fix that, as I have to update the forge version as well as conarmor and tic versions I'm building my mod on

**Comment by ToMe25** [comment]
Thanks ;)

**Comment by YaibaToKen** [comment]
I have a slight update on this, I can't test the situation as plusTIC crashes on the newest forge version and (being a lazy bastard)  don't really have the time to setup a dev environment with a different forge version (though I might have to if plusTIC isn't updated soon). I'll look into possible reasons for the materials not to show in the meantime though

**Comment by YaibaToKen** [comment]
@spyguy26 @ToMe25 could I ask you two to try it again using version 0.1.4 that is pending approval?

**Comment by ToMe25** [comment]
Ok. I will test it when the build is Approved.

**Comment by ToMe25** [comment]
Sorry, but it doesn't Fix that :)
All 16 Materials are anymore Missing.

**Comment by spyguy26** [comment]
Yep can confirm the materials are still missing

**Comment by YaibaToKen** [comment]
Do the missing materials not even show up in a freshly generated config file?

**Comment by spyguy26** [comment]
nope but I did have these interesting lines appear which seem to do nothing
    # Whether material._internal_render1.name should be used for armor parts
    S:_internal_render1=true

    # Whether material._internal_render2.name should be used for armor parts
    S:_internal_render2=true

    # Whether material._internal_render3.name should be used for armor parts
    S:_internal_render3=true

    # Whether material._internal_render4.name should be used for armor parts
    S:_internal_render4=true

    # Whether material._internal_renderstring.name should be used for armor parts
    S:_internal_renderstring=true

**Comment by YaibaToKen** [comment]
yeah, sorry, that's due to an incomplete rework of the config file

**Comment by ToMe25** [comment]
You should be able to Fix that by Changing the Folowing things:

Add `@EventBusSubscriber` directly over/under the @Mod Annotation.

Move `Config.syncConfig();` and `MaterialRegistration.registerFromToolMaterialStat();` from preInit to the Item Registration Event(with priority LOWEST because PlusTiC does it also)
Like so:
```java
    @SubscribeEvent(priority = EventPriority.LOWEST)
    public static void registerItems(RegistryEvent.Register<Item> e) {
    	Config.syncConfig();
        MaterialRegistration.registerFromToolMaterialStat();
    }
```

Change the Property Name to "enable_identifier" by Changing line 55 in File Config.java to
```java
propertiesMaterials.add(ArmoryExpansion.config.get(material.getIdentifier(), "enable_" + material.getIdentifier(), "true", "Global toggle for the " + material.getLocalizedName() + " material"));
```

Change the Material getting(MaterialRegistration.java line 60) to replace "enable_" with nothing like this
```java
Material material = TinkerRegistry.getMaterial(Config.propertiesMaterials.get(i).getName().replaceAll("enable_", ""));
```

PS: ~Sorry for all the Unformatted Code but i can't add returns in markdown codeblocks.~
Thanks to @TehSeph for commenting how to Fix Code Block Formatting.

**Comment by TehSeph** [comment]
@ToMe25 you can format code as blocks using \`\`\` instead of \` and you can color it by adding the language name on the same line as the first three ticks. Also, `Shift + Enter` for returns. :)

```java
@SubscribeEvent(priority = EventPriority.LOWEST)
public static void registerItems(RegistryEvent.Register<Item> e) {
    Config.syncConfig();
    MaterialRegistration.registerFromToolMaterialStat();
}
```

**Comment by ToMe25** [comment]
Thanks :) I will try it.

**Comment by ToMe25** [comment]
@YaibaToKen Why you aren't even reacting to this?
The last Comment is now a Month old.

**Comment by YaibaToKen** [comment]
So very sorry, real life got in the way and while I've made the changes mentioned in the comments, I'm still in the process of updating to a newer forge version

**Comment by ToMe25** [comment]
Thats Okay :)
I was just wondering why you haven't reacted as someone being so fast earlyer.

**Comment by ToMe25** [comment]
@YaibaToKen Thank you verry much!

**Comment by YaibaToKen** [comment]
> @YaibaToKen Thank you verry much!

Just doing my job :P @ToMe25 @TehSeph thank you two for the help
