### ISSUE TITLE
[QUESTION] Will this update with Minecraft?

### ISSUE THREAD

**Issue by SlimefrogSocial** [YaibaToKen/Armory-Expansion#83]
Will this be updated to newer versions of Minecraft such as 1.15?

**Comment by YaibaToKen** [comment]
As the mod depends on Tinker's Construct and Construct's Armory, i won't be updaed till those two and their respective dependencies are updated.

**Comment by CapivaraTupiniquim** [comment]
Minecraft 1.16.5?

**Comment by KiriCattus** [comment]
TheIllusiveC4 has not updated Construct's Armory yet so the answer for now will remain the same.
