### ISSUE TITLE
modpack

### ISSUE THREAD

**Issue by thedagonmantis** [YaibaToKen/Armory-Expansion#87]
hi I'm thedagonmantis im looking to use your mod in a modpack called dragon utopia
get back to me as soon as possible

**Comment by KiriCattus** [comment]
If a mod is on curseforge you automatically have rights to include it in a curseforge hosted modpack, if you wish to make a modpack for another launcher then you need to ask permission, is this for curseforge or for another launcher?

(When modders upload mods to curseforge it's in the ToS that we grant users the right to include the mod in a curseforge hosted modpack)

**Comment by YaibaToKen** [comment]
> If a mod is on curseforge you automatically have rights to include it in a curseforge hosted modpack, if you wish to make a modpack for another launcher then you need to ask permission, is this for curseforge or for another launcher?
> 
> (When modders upload mods to curseforge it's in the ToS that we grant users the right to include the mod in a curseforge hosted modpack)

As stated by ProxyNeko.
