### ISSUE TITLE
[Question] About Amory-Expansion

### ISSUE THREAD

**Issue by Cactusstudent** [YaibaToKen/Armory-Expansion#90]
You know, the day before yesterday, the Construct's Armory updated to Minecraft 1.16.5. Would you like to update the Armory Expansion to the 1.16.5, i think that will be great.

**Comment by jriwanek** [comment]
Please don't show up just to ask for newer mc builds, we're quite aware that newer mc versions are out, but we don't always have the time to update, we do infact have lives that we unfortunately have to prioritize first.
